USE mybrandplease;

CREATE TABLE IF NOT EXISTS home_testimonials (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  location VARCHAR(255) NULL,
  content TEXT NOT NULL,
  rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
  image_path VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_home_testimonials_active_order (is_active, sort_order, id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS home_offices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  country VARCHAR(150) NOT NULL,
  address TEXT NOT NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(80) NULL,
  image_path VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_home_offices_active_order (is_active, sort_order, id)
) ENGINE=InnoDB;
